---
title: "AMP_ves_summary_plots"
author: "Jessica McCordic"
date: "`r Sys.Date()`"
output: html_document
---

## Load libraries

```{r load libraries and helper script, include=FALSE, echo=FALSE}

#### Load libraries ####

# NOAA-approved tidyverse
tidyverse_short<-c("broom","cli","crayon","dbplyr","dplyr","dtplyr","forcats","ggplot2","googledrive","googlesheets4","hms","httr","jsonlite","lubridate","magrittr","modelr","pillar","purrr","readr","readxl","reprex","rlang","rstudioapi","rvest","stringr","tibble","tidyr","xml2") 
lapply(tidyverse_short, require, character.only = TRUE) 

library(scales)
library(ggalt)
library(ggsci)
library(ggdist)

theme_set(theme_bw(
  base_size = 14
))

# source helper file
source("code/AMP_summary_ves_funs.R")
```

## Load hourly presence datasets

```{r Load data}

#### Load compiled hourly presence table ####
# This is generated using Reformat_data_for_HP script

all_sites_hp <- read_csv("data/All_sites_tables/hourly_pres_allsites_local.csv")
all_sites_inout <- read_csv("data/All_sites_tables/total_ves_ins_out_by_site.csv")

```

## Reshape data for plotting

```{r reshape tables}

#### Add columns to original dataset to help group for plotting ####

all_sites_hp <- all_sites_hp |>
  mutate(
    # replace NA's with 0's to accurately incorporate hours with presence = 0
    Total_Vessels = replace_na(Total_Vessels, 0),
    total_inside = replace_na(total_inside, 0),
    total_inside_small = replace_na(total_inside_small, 0),
    
    # add categorical Y/N column for vessels present to calculate proportions
    ves_yn = ifelse(Total_Vessels == 0, "N","Y"),
    ins_ves_yn = ifelse(total_inside == 0, "N","Y"),
    ins_ves_small_yn = ifelse(total_inside_small == 0, "N","Y"),
    
    # add date without year to collapse across years
    Month = month(Begin_Date_loc),
    Week = isoweek(Begin_Date_loc),
    Day_month = mday(Begin_Date_loc),
    # re-create dates as all in the same year for plotting on single graph
    Date_noyr = as_date(paste0("2000", "-", Month, "-", Day_month), format = "%Y-%m-%d"),
    # get start date for each week
    Date_week = as_date(paste(Week,"1",sep = "-"), format = "%U-%u"),
    
    # add AMP Regional Networks and NPZ IDs based on Site_ID
    network = case_when(Site_ID == "CG" | Site_ID == "EP" | Site_ID == "WP" ~ "Temperate East",
                        Site_ID == "DNE" | Site_ID == "DSW" | Site_ID == "NGN"| Site_ID == "NGS" ~ "Northwest",
                        TRUE ~ "South-west"
    ),
    npz_id = case_when(
      # Cod Grounds
      Site_ID == "CG" ~ "CGMP", 
      # Solitary Islands
      Site_ID == "EP" | Site_ID == "WP" ~ "SIMP",
      # Dampier
      Site_ID == "DNE" | Site_ID == "DSW" ~ "DMP",
      # Ningaloo
      Site_ID == "NGN"| Site_ID == "NGS" ~ "NMP", 
      # Two Rocks
      Site_ID == "TRE" | Site_ID == "TRW" ~ "TRMP", 
      # Jurien
      Site_ID == "JSE" | Site_ID == "JNE" ~ "JMP", 
      # Geographe
      Site_ID == "GEO" ~ "GMP",
      # Murat
      Site_ID == "MRE" | Site_ID == "MRW" ~ "MMP",
      # South-west Corner
      Site_ID == "SWS" ~ "SWCMP" 
    )
  )

```

## Data gaps

Add in dates without coverage 
(this is still in progress)

```{r data gaps}


## Still need to troubleshoot this!!!

# load in deployment info CSV

# deploy_info <- read_csv("data/AMP_deployment_info.csv")
# 
# date_gaps <- deploy_info |>
#   mutate(Dep = gsub(pattern = "PARKSAUSTRALIA_",
#                     replacement = "",
#                     x = PROJECT_NAME)) |>
#   left_join(all_sites_hp, by = "Dep", multiple = "first") |>
#   select(c(Dep, all_dep_start, pre_site_gap_end, 
#            post_site_gap_start, all_dep_end,
#            dep_gap_start, dep_gap_end, 
#            network, npz_id, Site_ID))

```

## Data summary and visualization

### Total vessel presence per deployment

Raw total counts per deployments and vessels inside the NPZs
Deployment-level and NPZ-level info

```{r total presence}

# summarize in-out data to get n vessels used for I-O analysis per deployment
ins_out_counts <- all_sites_inout |>
  group_by(Dep_ID) |>
  summarize(n_ves_used_inout = n()) |>
  rename("Dep" = "Dep_ID")

# summarize full df to get counts per deployment
all_ves_by_site <- all_sites_hp |>
  group_by(network, npz_id, Site_ID, Dep) |>
  summarise(n_days = n_distinct(Begin_Date_loc),
            Total_ves_dep = sum(Total_Vessels, na.rm = TRUE),
            Total_inside = sum(total_inside, na.rm = TRUE),
            Total_inside_small = sum(total_inside_small, na.rm = TRUE),
            Inside_maneuver = sum(man_inside, na.rm = TRUE),
            Inside_maneuver_small = sum(man_inside_small, na.rm = TRUE),
            mean_per_day = Total_ves_dep/n_days,
            mean_overall = mean(Total_Vessels)) |>
  mutate(Inside_transit = Total_inside - Inside_maneuver,
         Inside_transit_small = Total_inside_small - Inside_maneuver_small) |>
  left_join(ins_out_counts, by = "Dep") |>
  mutate(
    prop_inside = Total_inside/n_ves_used_inout,
    total_outside = n_ves_used_inout - Total_inside,
    prop_inside_small = Total_inside_small/n_ves_used_inout,
    total_out_small = n_ves_used_inout - Total_inside_small)


all_ves_by_npz <- all_sites_hp |>
  group_by(network, npz_id, Site_ID, Dep) |>
  left_join(ins_out_counts, by = "Dep") |>
  ungroup() |>
  group_by(network, npz_id) |>
  summarise(n_days = n_distinct(Begin_Date_loc),
            Total_ves_npz = sum(Total_Vessels, na.rm = TRUE),
            Total_inside = sum(total_inside, na.rm = TRUE),
            Total_inside_small = sum(total_inside_small, na.rm = TRUE),
            
            Inside_maneuver = sum(man_inside, na.rm = TRUE),
            
            Inside_maneuver_small = sum(man_inside_small, na.rm = TRUE),
            mean_per_day = Total_ves_npz/n_days,
            
            n_used_inout = sum(n_ves_used_inout),
            
            mean_overall = mean(Total_Vessels),
           ) |>
  mutate(Inside_transit = Total_inside - Inside_maneuver,
         Inside_transit_small = Total_inside_small - Inside_maneuver_small,
         total_outside = n_used_inout - Total_inside,
         total_out_small = n_used_inout - Total_inside_small,
         prop_inside = Total_inside/n_used_inout,
         prop_inside_small = Total_inside_small/sum(n_used_inout))




all_ves_long <- all_ves_by_site |>
  pivot_longer(cols = -c(network, npz_id, Site_ID, Dep, n_days), values_to = "Ves_counts", names_to = "Ves_behav") |>
  # relevel categorical values for plotting
  mutate(Ves_behav = fct(Ves_behav),
         Ves_behav = fct_relevel(Ves_behav, c("Total_ves_dep","Total_inside_small", "Total_inside", "Inside_transit_small","Inside_maneuver_small", "Inside_transit","Inside_maneuver")),
         network = fct(network),
         network = fct_relevel(network, c("Temperate East","Northwest"))) |>
  # add diverging counts where inside values are negative for plotting
  mutate(ves_counts_diverge = ifelse(Ves_behav == "Total_inside" | Ves_behav == "Total_inside_small",Ves_counts*(-1),Ves_counts),
         npz_id = fct(npz_id),
         npz_id = fct_relevel(npz_id, c("CGMP","SIMP","DMP","NMP")))
```


```{r plots by deployment}
ggplot(data = all_ves_by_site,
       aes(x = Dep,
           y = Total_ves_dep,
           fill = npz_id)) +
  geom_col(show.legend = FALSE,
           color = "black") +
  scale_fill_viridis_d()+
  facet_grid(~network, 
             scales = "free_x", 
             space = "free", 
             drop = TRUE) +
  labs(x = "NPZ",
       y = "N vessels",
       title = "Total vessel counts") +
  theme(
    axis.text.x = element_text(angle = 90),
    strip.text.x = element_text(face = "bold")
    )


# counts including inside-outside
ggplot(data = all_ves_long,
       aes(x = npz_id,
           y = Ves_counts,
           fill = Ves_behav)) +
  geom_col(position = position_dodge()) +
  scale_fill_viridis_d()+
  # facet_grid(rows = vars(network), 
  #            scales = "free_x", 
  #            space = "free", 
  #            drop = TRUE) +
  labs(x = "NPZ",
       y = "N vessels",
       title = "Total vessel counts") +
  theme(
    axis.text.x = element_text(angle = 90),
    strip.text.x = element_text(face = "bold")
    )


# try inside vs outside proportion plot (fill to equal 1.0)
ggplot(data = all_ves_long |> 
         filter(Ves_behav == "total_outside" |
               Ves_behav == "Total_inside",
               npz_id != "SWCMP"),
       aes(x = npz_id,
           y = Ves_counts,
           fill = Ves_behav)) +
  geom_col(position = position_fill(reverse = TRUE)) +
  scale_fill_viridis_d(direction = -1)+
  labs(x = "NPZ",
       y = "Proportion vessels",
       fill = "Inside vs. Outside",
       title = "Inside-Outside Proportions") +
  theme(
    # axis.text.x = element_text(angle = 90),
    strip.text.x = element_text(face = "bold")
    )


# try diverging bar plot

breakvals <- seq(-200, 800, 200)

ggplot(data = all_ves_long |> 
         filter(Ves_behav == "total_outside" |
               Ves_behav == "Total_inside",
               npz_id != "SWCMP"),
       aes(x = npz_id,
           y = ves_counts_diverge,
           fill = Ves_behav)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  coord_flip()+
  scale_y_continuous(limits = c(-200, 800),
                     breaks = breakvals, 
                     labels = abs(breakvals))+
  scale_fill_viridis_d(direction = -1)+
  labs(x = "NPZ",
       y = "N vessels",
       fill = "Inside vs. Outside",
       title = "Inside-Outside Totals") +
  facet_grid(rows = vars(network),
             scales = "free",
             space = "free",
             drop = TRUE)+
  theme(
    # axis.text.x = element_text(angle = 90),
    strip.text.y = element_text(face = "bold")
    )

ggsave(paste0("figs/", "Ins_out_counts_npz.png"), width=10, height=6,
       units="in", dpi=300)

# Small vessels inside-outside

breakvals_small <- seq(-600, 600, 200)

ggplot(data = all_ves_long |> 
         filter(Ves_behav == "total_out_small" |
               Ves_behav == "Total_inside_small",
               npz_id != "SWCMP"),
       aes(x = npz_id,
           y = ves_counts_diverge,
           fill = Ves_behav)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  coord_flip()+
  scale_y_continuous(limits = c(-600, 600),
                     breaks = breakvals_small, 
                     labels = abs(breakvals_small))+
  scale_fill_viridis_d(direction = -1)+
  labs(x = "NPZ",
       y = "N vessels",
       fill = "Inside vs. Outside",
       title = "Inside-Outside Counts (Small Vessels)") +
   facet_grid(rows = vars(network),
             scales = "free",
             space = "free",
             drop = TRUE)+
  theme(
    # axis.text.x = element_text(angle = 90),
    strip.text.y = element_text(face = "bold")
    )

ggsave(paste0("figs/", "Ins_out_counts_small_npz.png"), width=10, height=6,
       units="in", dpi=300)


```



### Export CSV summary tables

```{r export tables}

# Total vessel presence
write_csv(all_ves_by_site, 
          file = "output/All_ves_by_dep.csv")
write_csv(all_ves_by_npz, 
          file = "output/All_ves_by_npz.csv")


```
